# Generated by Django 4.1 on 2022-10-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='newss',
        ),
        migrations.AddField(
            model_name='news',
            name='categores',
            field=models.ManyToManyField(to='news.category'),
        ),
    ]
