# Generated by Django 4.1 on 2022-10-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_category_newss_news_categores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/%h/%m/%s', verbose_name='Фото'),
        ),
    ]
