# Generated by Django 4.1 on 2022-10-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='photo',
            new_name='%Y-%m-%d-%H-%M-%S',
        ),
    ]
