# Generated by Django 4.1 on 2022-10-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_%y-%m-%d-%h-%m-%s_news_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='test',
            new_name='photo',
        ),
    ]
