# Generated by Django 4.1 on 2022-10-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_rename_photo_news_test_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='test_name',
            new_name='photo',
        ),
    ]
