# Generated by Django 4.1 on 2022-10-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='categores',
            field=models.ManyToManyField(blank=True, to='news.category'),
        ),
    ]
