# Generated by Django 4.1 on 2022-10-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_news_categores'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cost',
            field=models.FloatField(null=True, verbose_name='Ціна'),
        ),
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='news',
            name='we_have',
            field=models.BooleanField(default=False, verbose_name='Є в наявності?'),
        ),
    ]
