# Generated by Django 4.1 on 2022-10-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_news_cost_news_rating_news_we_have'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='news',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='we_have',
            field=models.BooleanField(blank=True, default=False, verbose_name='Є в наявності?'),
        ),
    ]
