# Generated by Django 4.1 on 2022-11-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_supercategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supercategory',
            options={'ordering': ['title'], 'verbose_name': 'Супер категорія', 'verbose_name_plural': 'Супер категорії'},
        ),
    ]
