# Generated by Django 4.1 on 2022-11-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_alter_supercategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
    ]
